global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rust_backend'
    static_configs:
      # Docker 內部網路中，backend 服務的 port 為 3000
      - targets: ['backend:3000']